service: facilitator-bot
frameworkVersion: "=1.21.1"

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
    - Action:
        - dynamodb:GetItem
        - dynamodb:GetRecords
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.${self:provider.stage}.ddb_candidates_table}
      Effect: Allow
  environment:
    slack_incomingWebHook: ${self:custom.${self:provider.stage}.slack_incomingWebHook}
    ddb_candidates_table: ${self:custom.${self:provider.stage}.ddb_candidates_table}
custom:
  dev: ${file(./conf/stg.yml)}
  stg: ${file(./conf/stg.yml)}

package:
  artifact: target/scala-2.12/facilitator_bot.jar

functions:
  remind_facilitator:
    handler: facilitator_bot.Handler
    events:
      - schedule: cron(25 1 ? * MON-FRI *)
        enabled: true
resources:
  Resources:
    CandidateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.${self:provider.stage}.ddb_candidates_table}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true